[formatter.ruff-check]
command = "ruff"
options = ["check", "--fix"]
excludes = []
includes = ["*.py", "*.pyi"]

[formatter.ruff-format]
command = "ruff"
options = ["format", "--line-length=120"]
excludes = []
includes = ["*.py", "*.pyi"]
